### ISSUE TITLE
intermittent issue cause mpv to hang on exit

### ISSUE THREAD

**Issue by ioangogo** [cniw/mpv-discordRPC#2]
Hi, im currently having a issue where mpv hangs on exit sometimes, I have only just opened GDB to see where it is getting stuck and it seems to be on the closing on the RPC connection in the discord provided RPC library. I am not sure if this is a upstream issue or an issue with how mpv-discordRPC tells the libary to quit

![image](https://user-images.githubusercontent.com/7449028/49152578-37bb1f00-f30b-11e8-9f6c-fd8a518bcf18.png)

**Comment by cniw** [comment]
@ioangogo on https://github.com/discordapp/discord-rpc/releases/tag/v3.4.0 said that
- Fixed the `disconnected()` callback not being fired

so this issue that caused by libdiscord-rpc problem.
