### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by Admiral124** [cniw/mpv-discordRPC#4]
Can't seem to get it working anymore. Following the install script and editing the config to use pypresence gives this error:

[mpv_discordRPC_lua_discordRPC] 
[mpv_discordRPC_lua_discordRPC] stack traceback:
[mpv_discordRPC_lua_discordRPC] 	[C]: in function 'require'
[mpv_discordRPC_lua_discordRPC] 	...in/.config/mpv/scripts/mpv-discordRPC_lua-discordRPC.lua:1: in main chunk
[mpv_discordRPC_lua_discordRPC] 	[C]: in ?
[mpv_discordRPC_lua_discordRPC] 	[C]: in ?
[mpv_discordRPC_lua_discordRPC] Lua error: ...in/.config/mpv/scripts/mpv-discordRPC_lua-discordRPC.lua:1: module 'ffi' not found:
[mpv_discordRPC_lua_discordRPC] 	no field package.preload['ffi']
[mpv_discordRPC_lua_discordRPC] 	no file '/usr/local/share/lua/5.2/ffi.lua'
[mpv_discordRPC_lua_discordRPC] 	no file '/usr/local/share/lua/5.2/ffi/init.lua'
[mpv_discordRPC_lua_discordRPC] 	no file '/usr/local/lib/lua/5.2/ffi.lua'
[mpv_discordRPC_lua_discordRPC] 	no file '/usr/local/lib/lua/5.2/ffi/init.lua'
[mpv_discordRPC_lua_discordRPC] 	no file '/usr/share/lua/5.2/ffi.lua'
[mpv_discordRPC_lua_discordRPC] 	no file '/usr/share/lua/5.2/ffi/init.lua'
[mpv_discordRPC_lua_discordRPC] 	no file './ffi.lua'
[mpv_discordRPC_lua_discordRPC] 	no file '/home/lain/.config/mpv/scripts/ffi.lua'
[mpv_discordRPC_lua_discordRPC] 	no file '/usr/local/lib/lua/5.2/ffi.so'
[mpv_discordRPC_lua_discordRPC] 	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/ffi.so'
[mpv_discordRPC_lua_discordRPC] 	no file '/usr/lib/lua/5.2/ffi.so'
[mpv_discordRPC_lua_discordRPC] 	no file '/usr/local/lib/lua/5.2/loadall.so'
[mpv_discordRPC_lua_discordRPC] 	no file './ffi.so'

**Comment by cniw** [comment]
The error message says that your rpc wrapper settings are still using `lua-discordRPC` and in your PC installed `lua52` instead of `luajit`.
If you want to use `pypresence` as a rpc wrapper, change `mpv_discordRPC.conf` file in `script-opts` folder at the first line become `rpc_wrapper=pypresence`.

**Comment by Admiral124** [comment]
My mistake. I was editing the file in the scripts folder, not script-opts. It's working now (even though those errors still come up when launching mpv in the terminal).
